import crypto from "node:crypto";
import { and, eq } from "drizzle-orm";
import { dailyChallenges, dailyRuns } from "../drizzle/schema";
import { AuctionRules, calculateAuctionSlotCost, getAuctionRevealLimit, type AuctionClue } from "../shared/auctionRules";
import { MODERN_DAILY_MODES } from "../shared/dailyModes";
import { normalizeGameWord } from "@shared/motus";
import { getDailyMysteryChallenge, getDailyPyramidChallenge, getRandomMotusWord, getDb, validateDailyPyramidStep } from "./db";

export type DailyMode = "mystery" | "pyramid" | "auction";
export type DailyScope = "official" | "practice";
type MysteryChallengePublic = { tokens: string[]; grammaticalCategory: string | null };
type MysteryChallengeSecret = { lemma: string };
type PyramidChallenge = { startWord: string; finalLength: number };
type AuctionChallengePublic = { length: number };
type AuctionChallengeSecret = { lemma: string };
type MysteryState = { manualReveals: number[]; clues: Array<"grammar">; guesses: string[] };
type PyramidState = { words: string[] };
type AuctionState = { budget: number; revealed: Record<string, string>; clues: AuctionClue[]; guesses: Array<{ guess: string; isCorrect: boolean }> };
type RunState = MysteryState | PyramidState | AuctionState;
type StoredChallenge = { id: number; dailyDate: string; mode: DailyMode; publicData: string; secretData: string };
type StoredRun = { id: string; challengeId: number; ownerKey: string; dailyDate: string; mode: DailyMode; runNonce: string; status: "active" | "won" | "lost" | "abandoned"; stateData: string; attempts: number; score: number; version: number; startedAt: Date; completedAt: Date | null };
const utcDay = (now = new Date()) => now.toISOString().slice(0, 10);
const runId = () => crypto.randomBytes(24).toString("base64url");
const parse = <T,>(value: string): T => { try { return JSON.parse(value) as T; } catch { throw new Error("État de partie corrompu."); } };
function initialState(mode: DailyMode): RunState { return mode === "mystery" ? { manualReveals: [], clues: [], guesses: [] } : mode === "pyramid" ? { words: [] } : { budget: AuctionRules.startingBudget, revealed: {}, clues: [], guesses: [] }; }

async function generateChallenge(mode: DailyMode) {
  if (mode === "mystery") { const challenge = await getDailyMysteryChallenge(); if (!challenge) throw new Error("Aucun défi Mystère n’est disponible."); return { publicData: { tokens: challenge.tokens, grammaticalCategory: challenge.category ?? null } satisfies MysteryChallengePublic, secretData: { lemma: challenge.lemma } satisfies MysteryChallengeSecret }; }
  if (mode === "pyramid") { const challenge = await getDailyPyramidChallenge(); if (!challenge) throw new Error("Aucune pyramide de lettres n’est disponible."); const data = { startWord: challenge.startWord, finalLength: challenge.finalLength } satisfies PyramidChallenge; return { publicData: data, secretData: data }; }
  const word = await getRandomMotusWord(AuctionRules.minWordLength, 8); if (!word) throw new Error("Aucun défi Enchères n’est disponible."); return { publicData: { length: word.lemma.length } satisfies AuctionChallengePublic, secretData: { lemma: word.lemma } satisfies AuctionChallengeSecret };
}
async function getOrCreateChallenge(mode: DailyMode, date: string): Promise<StoredChallenge> {
  const db = await getDb(); if (!db) throw new Error("La persistance des défis est indisponible.");
  const [existing] = await db.select().from(dailyChallenges).where(and(eq(dailyChallenges.dailyDate, date), eq(dailyChallenges.mode, mode))).limit(1); if (existing) return existing as StoredChallenge;
  const generated = await generateChallenge(mode); await db.insert(dailyChallenges).values({ dailyDate: date, mode, publicData: JSON.stringify(generated.publicData), secretData: JSON.stringify(generated.secretData) }).onDuplicateKeyUpdate({ set: { dailyDate: date } });
  const [stored] = await db.select().from(dailyChallenges).where(and(eq(dailyChallenges.dailyDate, date), eq(dailyChallenges.mode, mode))).limit(1); if (!stored) throw new Error("Impossible de créer le défi du jour."); return stored as StoredChallenge;
}
async function loadOwnedRun(ownerKey: string, id: string) { const db = await getDb(); if (!db) throw new Error("La persistance des défis est indisponible."); const [run] = await db.select().from(dailyRuns).where(and(eq(dailyRuns.id, id), eq(dailyRuns.ownerKey, ownerKey))).limit(1); if (!run) throw new Error("Cette session de jeu n’existe pas ou ne vous appartient pas."); const [challenge] = await db.select().from(dailyChallenges).where(eq(dailyChallenges.id, run.challengeId)).limit(1); if (!challenge) throw new Error("Le défi associé à cette session est introuvable."); return { run: run as StoredRun, challenge: challenge as StoredChallenge }; }
async function updateRun(ownerKey: string, run: StoredRun, next: { state: RunState; attempts?: number; score?: number; status?: StoredRun["status"]; completed?: boolean }) { const db = await getDb(); if (!db) throw new Error("La persistance des défis est indisponible."); const result = await db.update(dailyRuns).set({ stateData: JSON.stringify(next.state), attempts: next.attempts ?? run.attempts, score: next.score ?? run.score, status: next.status ?? run.status, version: run.version + 1, completedAt: next.completed ? new Date() : run.completedAt }).where(and(eq(dailyRuns.id, run.id), eq(dailyRuns.ownerKey, ownerKey), eq(dailyRuns.version, run.version))); const writeResult = Array.isArray(result) ? result[0] : result; const affectedRows = Number((writeResult as { rowsAffected?: number; affectedRows?: number }).rowsAffected ?? (writeResult as { affectedRows?: number }).affectedRows ?? 0); if (affectedRows !== 1) throw new Error("La partie a été modifiée dans un autre onglet. Actualisez puis réessayez."); return loadOwnedRun(ownerKey, run.id); }
function mysterySnapshot(run: StoredRun, challenge: StoredChallenge) { const state = parse<MysteryState>(run.stateData); const data = parse<MysteryChallengePublic>(challenge.publicData); const elapsedSeconds = Math.max(0, Math.floor((Date.now() - run.startedAt.getTime()) / 1_000)); const automaticCount = Math.min(data.tokens.length, 1 + Math.floor(elapsedSeconds / 3)); const revealed = new Set<number>([...Array.from({ length: automaticCount }, (_, index) => index), ...state.manualReveals]); const rawScore = Math.max(0, MODERN_DAILY_MODES.mystery.initialScore - elapsedSeconds * MODERN_DAILY_MODES.mystery.penaltyPerSecond - state.manualReveals.length * MODERN_DAILY_MODES.mystery.manualRevealCost - state.clues.length * MODERN_DAILY_MODES.mystery.bonusHintCost - state.guesses.length * MODERN_DAILY_MODES.mystery.penaltyPerWrongGuess); const intuitionEligible = data.tokens.length > 0 && revealed.size / data.tokens.length < MODERN_DAILY_MODES.mystery.intuitionBonusThreshold; return { runId: run.id, mode: "mystery" as const, status: run.status, score: run.status === "won" ? run.score : revealed.size >= data.tokens.length ? 0 : rawScore, elapsedSeconds, tokens: data.tokens, revealedIndices: Array.from(revealed).sort((a, b) => a - b), grammaticalCategory: state.clues.includes("grammar") ? data.grammaticalCategory : null, attempts: state.guesses, intuitionEligible }; }
function pyramidSnapshot(run: StoredRun, challenge: StoredChallenge) { const data = parse<PyramidChallenge>(challenge.publicData); return { runId: run.id, mode: "pyramid" as const, status: run.status, score: run.score, startWord: data.startWord, finalLength: data.finalLength, words: parse<PyramidState>(run.stateData).words }; }
function auctionSnapshot(run: StoredRun, challenge: StoredChallenge) { const state = parse<AuctionState>(run.stateData); const data = parse<AuctionChallengePublic>(challenge.publicData); const secret = parse<AuctionChallengeSecret>(challenge.secretData); const revealedCount = Object.keys(state.revealed).length; const vowels = secret.lemma.split("").filter((letter) => /[AEIOUYÀÂÄÉÈÊËÎÏÔÖÙÛÜŸ]/i.test(letter)).length; const pattern = secret.lemma.split("").map((letter) => /[AEIOUYÀÂÄÉÈÊËÎÏÔÖÙÛÜŸ]/i.test(letter) ? "V" : "C").join("-"); return { runId: run.id, mode: "auction" as const, status: run.status === "active" && state.budget === 0 ? "last_chance" : run.status, score: run.score, budget: state.budget, length: data.length, revealedPositions: state.revealed, boughtClues: state.clues, attempts: state.guesses, maxAttempts: AuctionRules.maxAttempts, maxBuyablePositions: getAuctionRevealLimit(data.length), nextLetterCost: calculateAuctionSlotCost(revealedCount), revealLimitReached: revealedCount >= getAuctionRevealLimit(data.length), availableClues: { vowelCount: state.clues.includes("vowel_count") ? vowels : null, pattern: state.clues.includes("pattern") ? pattern : null } }; }
function snapshot(run: StoredRun, challenge: StoredChallenge) { return run.mode === "mystery" ? mysterySnapshot(run, challenge) : run.mode === "pyramid" ? pyramidSnapshot(run, challenge) : auctionSnapshot(run, challenge); }

export async function startDailyRun(ownerKey: string, mode: DailyMode, scope: DailyScope) { const db = await getDb(); if (!db) throw new Error("La persistance des défis est indisponible."); const date = utcDay(); const challenge = await getOrCreateChallenge(mode, date); const runNonce = scope === "official" ? "official" : runId(); if (scope === "official") { const [existing] = await db.select().from(dailyRuns).where(and(eq(dailyRuns.ownerKey, ownerKey), eq(dailyRuns.dailyDate, date), eq(dailyRuns.mode, mode), eq(dailyRuns.runNonce, runNonce))).limit(1); if (existing) return snapshot(existing as StoredRun, challenge); } const id = runId(); await db.insert(dailyRuns).values({ id, challengeId: challenge.id, ownerKey, dailyDate: date, mode, runNonce, stateData: JSON.stringify(initialState(mode)) }); const { run } = await loadOwnedRun(ownerKey, id); return snapshot(run, challenge); }
export async function getDailyRun(ownerKey: string, id: string) { const { run, challenge } = await loadOwnedRun(ownerKey, id); return snapshot(run, challenge); }
export async function revealDailyMystery(ownerKey: string, id: string, action: "word" | "grammar", index?: number) { const { run, challenge } = await loadOwnedRun(ownerKey, id); if (run.mode !== "mystery" || run.status !== "active") throw new Error("Cette partie Mystère est terminée."); const state = parse<MysteryState>(run.stateData); const data = parse<MysteryChallengePublic>(challenge.publicData); if (action === "grammar") { if (!state.clues.includes("grammar")) state.clues.push("grammar"); } else { if (index === undefined || index < 0 || index >= data.tokens.length) throw new Error("Indice hors limite."); const elapsed = Math.floor((Date.now() - run.startedAt.getTime()) / 1_000); const auto = new Set(Array.from({ length: Math.min(data.tokens.length, 1 + Math.floor(elapsed / 3)) }, (_, value) => value)); if (!auto.has(index) && !state.manualReveals.includes(index)) state.manualReveals.push(index); } const updated = await updateRun(ownerKey, run, { state }); return snapshot(updated.run, updated.challenge); }
export async function attemptDailyMystery(ownerKey: string, id: string, word: string) { const { run, challenge } = await loadOwnedRun(ownerKey, id); if (run.mode !== "mystery" || run.status !== "active") throw new Error("Cette partie Mystère est terminée."); const state = parse<MysteryState>(run.stateData); const secret = parse<MysteryChallengeSecret>(challenge.secretData); const valid = normalizeGameWord(word) === normalizeGameWord(secret.lemma); if (!valid) state.guesses.push(normalizeGameWord(word)); const before = mysterySnapshot(run, challenge); const score = valid ? Math.min(1200, before.intuitionEligible ? Math.round(before.score * MODERN_DAILY_MODES.mystery.intuitionBonusMultiplier) : before.score) : run.score; const updated = await updateRun(ownerKey, run, { state, attempts: run.attempts + 1, score, status: valid ? "won" : "active", completed: valid }); return { ...snapshot(updated.run, updated.challenge), valid, lemma: valid ? secret.lemma : undefined }; }
export async function attemptDailyPyramid(ownerKey: string, id: string, word: string) { const { run, challenge } = await loadOwnedRun(ownerKey, id); if (run.mode !== "pyramid" || run.status !== "active") throw new Error("Cette pyramide est terminée."); const state = parse<PyramidState>(run.stateData); const data = parse<PyramidChallenge>(challenge.publicData); const previousWord = state.words.at(-1) ?? data.startWord; const validation = await validateDailyPyramidStep(previousWord, word); if (!validation.valid) return { ...snapshot(run, challenge), valid: false, reason: validation.reason }; state.words.push(validation.word); const solved = validation.word.length >= data.finalLength; const updated = await updateRun(ownerKey, run, { state, attempts: run.attempts + 1, score: run.score + 20, status: solved ? "won" : "active", completed: solved }); return { ...snapshot(updated.run, updated.challenge), valid: true, solved }; }
export async function revealDailyAuctionLetter(ownerKey: string, id: string, index: number) { const { run, challenge } = await loadOwnedRun(ownerKey, id); if (run.mode !== "auction" || run.status !== "active") throw new Error("Cette partie Enchères est terminée."); const state = parse<AuctionState>(run.stateData); const data = parse<AuctionChallengePublic>(challenge.publicData); const secret = parse<AuctionChallengeSecret>(challenge.secretData); if (index < 0 || index >= data.length) throw new Error("Indice hors limite."); if (state.revealed[String(index)]) return snapshot(run, challenge); if (Object.keys(state.revealed).length >= getAuctionRevealLimit(data.length)) throw new Error("Quota de lettres atteint."); const cost = calculateAuctionSlotCost(Object.keys(state.revealed).length); if (state.budget < cost) throw new Error("Fonds insuffisants."); state.budget -= cost; state.revealed[String(index)] = secret.lemma[index]!.toLocaleUpperCase("fr-FR"); const updated = await updateRun(ownerKey, run, { state }); return snapshot(updated.run, updated.challenge); }
export async function revealDailyAuctionClue(ownerKey: string, id: string, clue: Exclude<AuctionClue, "length">) { const { run, challenge } = await loadOwnedRun(ownerKey, id); if (run.mode !== "auction" || run.status !== "active") throw new Error("Cette partie Enchères est terminée."); const state = parse<AuctionState>(run.stateData); if (state.clues.includes(clue)) return snapshot(run, challenge); const cost = clue === "vowel_count" ? AuctionRules.costs.vowelCount : AuctionRules.costs.consonantPattern; if (state.budget < cost) throw new Error("Fonds insuffisants."); state.budget -= cost; state.clues.push(clue); const updated = await updateRun(ownerKey, run, { state }); return snapshot(updated.run, updated.challenge); }
export async function attemptDailyAuction(ownerKey: string, id: string, word: string) { const { run, challenge } = await loadOwnedRun(ownerKey, id); if (run.mode !== "auction" || run.status !== "active") throw new Error("Cette partie Enchères est terminée."); const state = parse<AuctionState>(run.stateData); const secret = parse<AuctionChallengeSecret>(challenge.secretData); const guess = normalizeGameWord(word); const valid = guess === normalizeGameWord(secret.lemma); state.guesses.push({ guess, isCorrect: valid }); if (!valid) state.budget = Math.max(0, state.budget - AuctionRules.penalties.wrongAttempt); const lost = !valid && (state.guesses.length >= AuctionRules.maxAttempts || state.budget === 0); const score = valid ? state.budget * 10 + Math.max(0, AuctionRules.maxAttempts - state.guesses.length) * 50 : run.score; const updated = await updateRun(ownerKey, run, { state, attempts: run.attempts + 1, score, status: valid ? "won" : lost ? "lost" : "active", completed: valid || lost }); return { ...snapshot(updated.run, updated.challenge), valid, lemma: valid || lost ? secret.lemma : undefined }; }
